#! /bin/bash

# Updating the repo list
echo "Updating the System.."
sudo apt update 

# Install Apache
echo "Checking if Nignx is installed and running or not"
if command -v nginx >/dev/null 2>&1; then
        echo "Nginx installation detected! Removing it from the system"
        sudo apt purge nginx -y
        sudo apt autoremove -y
        echo "Installing apache2...."
        sudo apt install apache2 apache2-utils -y
        sudo systemctl enable apache2
else
        echo "Installing apache2...."
        sudo apt install apache2 apache2-utils -y
        sudo systemctl enable apache2
fi
echo "Apache Installation is Done."

# Storing values for mysql root password
 read -p 'wordpress_db_name [wp_db]: ' wordpress_db_name
 read -p 'db_root_password: ' db_root_password
 echo

# Install PHP
apt-get install php libapache2-mod-php php-mysql -y

# Install MySQL DB Server
export DEBIAN_FRONTEND="noninteractive"
debconf-set-selections <<< "mysql-server mysql-server/root_password password $db_root_password"
debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $db_root_password"
apt-get install mysql-server mysql-client -y

# Install Latest WordPress
rm /var/www/html/index.*
wget -c http://wordpress.org/latest.tar.gz
tar -xzvf latest.tar.gz
rsync -av wordpress/* /var/www/html/

# Set Permissions
chown -R www-data:www-data /var/www/html/
chmod -R 755 /var/www/html/

# Configure WordPress Database  
mysql -u root -p $db_root_password <<QUERY_INPUT
CREATE DATABASE $wordpress_db_name;
GRANT ALL PRIVILEGES ON $wordpress_db_name.* TO 'root'@'localhost' IDENTIFIED BY '$db_root_password';
FLUSH PRIVILEGES;
EXIT
QUERY_INPUT

# Add Database Credentias in wordpress
cd /var/www/html/
sudo mv wp-config-sample.php wp-config.php
perl -pi -e "s/database_name_here/$wordpress_db_name/g" wp-config.php
perl -pi -e "s/username_here/root/g" wp-config.php
perl -pi -e "s/password_here/$db_root_password/g" wp-config.php

# Enabling Mod Rewrite
a2enmod rewrite
php5enmod mcrypt

# Install PhpMyAdmin
apt-get install phpmyadmin -y

# Configure PhpMyAdmin  
echo 'Include /etc/phpmyadmin/apache.conf' >> /etc/apache2/apache2.conf

# Restart Apache and Mysql
service apache2 restart
service mysql restart
