#!/bin/bash
echo "Please Enter Number1"
read num1
echo "Please Enter Number2"
read num2

if [ $num1 -gt $num2 ]
then
	echo "Number1 is Greater!"
elif [ $num2 -gt $num1 ]
then
	echo "Number2 is Greater!"
else
	echo "Invalid Input!"
fi

